// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"YED_Hospital","status":true,"description":"Provides hospital feature, where party spend their money for\nrecovery.","parameters":{"[Default Price]":"","HP Price":"10","MP Price":"20","State Price":"100","[Visual Setting]":"","Nurse Face":"People4, 1","Nurse Name":"Loli","Nurse Message":"Hello,\\nHow can I halp you?","Heal One Help":"Heals members individually.","Heal All Help (Treat)":"Heals all members at cost %1G.","Heal All Help (Healthy)":"All members are healthy.","Exit Help":"Go out.","Actor Help (Treat)":"%1 needs treatment.","Actor Help (Healthy)":"%1 is healthy.","Heal One Command":"Heal One","Heal All Command":"Heal All","Exit Command":"Exit","Text Alignment":"center"}}
];
