// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"YED_Tilemap","status":true,"description":"","parameters":{}},
{"name":"YED_LunaEngine","status":true,"description":"","parameters":{}}
];
